### ISSUE TITLE
Questions about the tweets

### ISSUE THREAD

**Issue by hotchilipowder** [anmolpanda/NivaDuck_public#1]
Hello, it looks great to build a dataset for politicians on social media.
But the current project seems to only offer account information (twitter handles), and not tweets? 
Is there a link to provide relevant tweets? 

Thanks

**Comment by libbyh** [comment]
Twitter prohibits sharing of the actual tweets. If you're affiliated with the University of Michigan or have a collaborator at UM, you can check out https://github.com/casmlab/politicians-tweets.
